### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by qyz1106** [CrazyRedMachine/chu2to3#3]
Hardware: YubiDeck
Software: SDHD 2.05

When I tried to build within bin, I encoutered this problem in meson:

D:\Chunithm\SDHD_2.05\app\bin>meson setup build32 --buildtype=release
The Meson build system
Version: 0.63.0
Source dir: D:\Chunithm\SDHD_2.05\app\bin
Build dir: D:\Chunithm\SDHD_2.05\app\bin\build32
Build type: native build
Project name: rb_dll
Project version: 0.1.0
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 151, in run
  File "mesonbuild\msetup.py", line 303, in run
  File "mesonbuild\msetup.py", line 186, in generate
  File "mesonbuild\msetup.py", line 208, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 331, in __init__
  File "mesonbuild\interpreterbase\interpreterbase.py", line 119, in parse_project
  File "mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 462, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
  File "mesonbuild\interpreterbase\decorators.py", line 580, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 1231, in func_project
  File "mesonbuild\mesonlib\vsenv.py", line 105, in setup_vsenv
  File "mesonbuild\mesonlib\vsenv.py", line 65, in _setup_vsenv
  File "json\__init__.py", line 341, in loads
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 671: invalid start byte

meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

Any idea how to solve it?

**Comment by CrazyRedMachine** [comment]
why would you try to build within bin folder?? also if you're not trying to mod the program you should just grab the precompiled binaries from the release page ( https://github.com/CrazyRedMachine/chu2to3/releases/download/v1.2/chu2to3_v1.2.zip )

if you're trying to recompile your own variant then first make yourself a separate clean dev environment..

**Comment by qyz1106** [comment]
Thanks for clarifying! However, the game seems to crash when initializing io device. I used the chuniio from plost.
